### ISSUE TITLE
Issue with executing Cloud formation template from Jenkins- error- Unable to locate credentials. 

### ISSUE THREAD

**Issue by msdops20** [ABBANAPURI0445/URSI#3]
I have configured a Master-Slave  Jenkins setup for this project
Jenkins Master 
Slave machine with java and aws cli installed and "aws configure"

_Pipeline script:_
node('awscli-cf') {
    stage('stackexe') {
    sh label: '', script: 'aws cloudformation create-stack --stack-name myProjectstack --template-url https://github.com/msdops20/assignmentTest/blob/master/cloudFormation-jenkins-Oregon-23july.json --region \'us-west-2\''
}
}
----------------------------------------------------------
Issue: I did run "aws configure" on Slave machine where I have installed aws cli, 
I am not sure about the settings at this point.
Console OutPut below--------

Console OutputStarted by user msdops20
Running in Durability level: MAX_SURVIVABILITY[Pipeline]
 Start of Pipeline[Pipeline] nodeRunning on awscli-slave in /home/awsuser/workspace/test-cf-stack[Pipeline] {[Pipeline] stage[Pipeline] { (stackexe)[Pipeline] 
sh+ aws cloudformation create-stack --stack-name myProjectstack --template-url https://github.com/msdops20/assignmentTest/blob/master/cloudFormation-jenkins-Oregon-23july.json --region us-west-2
Unable to locate credentials. 
You can configure credentials by running "aws configure".[Pipeline] }[Pipeline] // stage[Pipeline] }[Pipeline] // node[Pipeline] End of PipelineERROR: script returned exit code 255Finished: FAILURE

**Comment by ABBANAPURI0445** [comment]
Hi Meena garu
if resolve issue please close with Solution

**Comment by msdops20** [comment]
I was able to resolve the issue as advised:
Below was the resolution to resolve the issue-
1)make sure to run "aws config" cmd from username example - awsuser that was created on the slave ec2 machine on which aws cli was installed.
2)If cloudformation template is called from github, first call - git clone, and then in aws cli - create-stack command provide  complete path to location of json file on slave machine where json file is copied to upon git clone.
Below is the Pipeline script:

node('awscli-cf') {
    stage('SCM'){
        git 'https://github.com/msdops20/assignmentTest.git'
    }
        stage('stackexe') {
    sh label: '', script: 'aws cloudformation create-stack --stack-name myProjectstack --template-body file:///home/awsuser//workspace/test-cf-stack/cloudFormation-jenkins-Oregon-23july.json --region \'us-west-2\''
}
}
