### ISSUE TITLE
sonarqube integration to jenkins error

### ISSUE THREAD

**Issue by Rupini93** [ABBANAPURI0445/URSI#4]
I was not able to ADD token id to the sonarqube configuration... While I was clicking "ADD" option I couldnt see any jenkins option down there... mentioned in below diagram...
And jfrog integration was done sucessfully..
Can anybody give suggestions...
thanks..
![Screenshot (980)](https://user-images.githubusercontent.com/57709400/86384766-12f3ff80-bc44-11ea-9a46-4cc1c119c0bd.png)

**Comment by ABBANAPURI0445** [comment]
hi
uninstall plugin and reinstall again (sonaq scanner) plugin
restart jenkins "systemctl restart jenkins"

**Comment by Rupini93** [comment]
I did the same as well... uninstalled and again installed

**Comment by ABBANAPURI0445** [comment]
install plugin and click on restart after install

**Comment by Rupini93** [comment]
Can I  know the steps while configuring sonarqube web page...
From generating token onwards....

**Comment by Rupini93** [comment]
> install plugin and click on restart after install

ok sir will do it again

**Comment by ABBANAPURI0445** [comment]
what happen rupini
did you try

**Comment by Rupini93** [comment]
I will try again and inform you sir

**Comment by Rupini93** [comment]
for uninstalling it was taking time

**Comment by ABBANAPURI0445** [comment]
yes, please wait until finish

**Comment by Rupini93** [comment]
yes sir, it was working..
