### ISSUE TITLE
getting error while launching agent docker-slave

### ISSUE THREAD

**Issue by Rupini93** [ABBANAPURI0445/URSI#9]
First I installed docker and later installed java..
gave sudo permissions with root user..
And configured node setup for docker..
![Screenshot (1338)](https://user-images.githubusercontent.com/57709400/87192298-09edd880-c2ab-11ea-9ce2-42b75a1aae56.png)
![Screenshot (1340)](https://user-images.githubusercontent.com/57709400/87192301-0a866f00-c2ab-11ea-9ff8-6dc0efe7a9b9.png)

**Comment by ABBANAPURI0445** [comment]
hi 
/home/ubuntu so you need to add ubuntu user credential 
if you want to use dummy user please change remote directory /home/ubuntu to /home/dummy
